language: node_js

os:
  - osx
  - linux

node_js:
  - "0.12"
  - "0.10"

env:
  global:
   - secure: aeo6Pg3hokp+BEaotoqE6L0fW59/bDyIfehU/Aapdozwd1rViHKVfAqUZr6hk9B0yzksDeGwkHg1/5AdqRA0R1VgkOzZdaxdlfoW3wIltEszGjk8LPcVVpQnPigfz4w4VbB5qBe/cVkTZohOdd446VjAZ+IGjKWsSI5NYC69lI8=
   - secure: ErvlZ2XHm0CKC9PBco3IXma7QWuc9rjeHH4It4a0UbsfPJRlbPLg24EPoH39818X543AniRPJzkqOQJkj6EhAn+lkjGCNlOZAa3A+DlhOP34/zlXRRjKLQC/XoTkMBEk5XwIPXNsISunC6U0b+nsd3zI5GncGeXVy2y5giZMpog=
   - secure: DXNRb33AcdmIRcDkQ/9cG8/gXpMuYr6xqOMwbdgQ5OQgQLIhWjvpgpqKBIii9JJ1qFKbM6TUo3njP/m9vkGrP1R9t3CRTP2alpRgCUmQ7bk9dyymrCW0lTFbPbGWANDEeZxdQD5tJ35uOQOR+w/sP2/qR4ROeYqytOTwHxsvZQs=

before_install:
- export PATH=./node_modules/.bin/:$PATH

install:
- npm install --build-from-source

after_install:
- npm test

script:
- node-pre-gyp package unpublish publish
- node-pre-gyp clean

after_success:
- node-pre-gyp info